using GraphicIDE.Properties;

namespace GraphicIDE;

public static class MyImages {
    public static readonly Bitmap
        whileArrowDownImg = new(Resources.whileArrowDown),
        whileArrowUpImg = new(Resources.whileArrowUp),
        forArrowDownImg = new(Resources.forArrowDown),
        forArrowUpImg = new(Resources.forArrowUp),
        emptyListImg = new(Resources.emptyList),
        emptyTupleImg = new(Resources.emptyTuple),
        lightmodeImg = new(Resources.brightnessBarSymbol),
        shortArrowG = new(Resources.shortArrowGreen),
        shortArrowR = new(Resources.shortArrowRed),
        keyboardImg = new(Resources.keyboard),
        settingsImg = new(Resources.Settings),
        printerImg = new(Resources.printer),
        consoleImg = new(Resources.console),
        hashtagImg = new(Resources.hastag),
        searchImg = new(Resources.search),
        renameImg = new(Resources.rename),
        returnImg = new(Resources.Arrow),
        play3dImg = new(Resources.play1),
        divmodImg = new(Resources.divmod),
        filterImg = new(Resources.filter),
        floatImg = new(Resources.float12),
        rulerImg = new(Resources.ruler),
        roundImg = new(Resources.round),
        truckImg = new(Resources.truck),
        pasteImg = new(Resources.paste),
        tupleImg = new(Resources.tuple),
        debugImg = new(Resources.bug),
        lockImg = new(Resources.lockImg),
        boolImg = new(Resources.boolXY),
        listImg = new(Resources.list),
        playImg = new(Resources.play),
        copyImg = new(Resources.copy),
        noneImg = new(Resources.None),
        plusImg = new(Resources.plus),
        passImg = new(Resources.pass),
        intImg = new(Resources.int1234),
        dotImg = new(Resources.dot),
        sumImg = new(Resources.sum),
        maxImg = new(Resources.max),
        minImg = new(Resources.min),
        strImg = new(Resources.yarn),
        xImg = new(Resources.red_X);
}